name: fluent_result
description: Result is an object indicating success or failure of an operation.
version: 4.0.1
homepage: https://github.com/AndrewPiterov/fluent_result

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  coverage: ^1.0.1
  test: ^1.16.8
  pedantic: ^1.11.0

flutter:
