name: fluent_result
description: Result is an object indicating success or failure of an operation.
version: 1.0.0+1
homepage: https://github.com/AndrewPiterov/fluent_result

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
