name: fluent_result
description: Result is an object indicating success or failure of an operation.
version: 4.3.0
homepage: https://github.com/AndrewPiterov/fluent_result

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  quiver: ^3.0.1+1

dev_dependencies:
  coverage: ^1.0.3
  given_when_then_unit_test: ^0.0.6
  lint: ^1.7.2
  shouldly: ^0.2.4
  test: ^1.19.5