name: fluent_result
description: Result is an object indicating success or failure of an operation.
version: 2.0.0+1
homepage: https://github.com/AndrewPiterov/fluent_result

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  coverage: ^0.14.2
  test: ^1.15.7
  pedantic: ^1.9.2

flutter:
